language: node_js
node_js:
  - "12.16.1"
script:
  - echo "Deploying"

before_script:
  - npm install -g firebase-tools
  - npm install -g @vue/cli@latest
  - npm install

script:
  - npm run build

after_success:  
  echo "Deployed"
  #- firebase deploy --token $FKEY

